DROP TABLE IF EXISTS Groups;
CREATE TABLE Groups (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(255) UNIQUE NOT NULL,
);

DROP TABLE IF EXISTS Students;
CREATE TABLE Students (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(255) UNIQUE NOT NULL,
    Group_id INTEGER,
    FOREIGN KEY (Group_id) REFERENCES Groups (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

DROP TABLE IF EXISTS Teachers;
CREATE TABLE Teachers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(255) UNIQUE NOT NULL,
);

DROP TABLE IF EXISTS Subjects;
CREATE TABLE Subjects (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(255) UNIQUE NOT NULL,
    Teaher_id INTEGER,
    FOREIGN KEY (Group_id) REFERENCES Group (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);