DROP TABLE IF EXISTS Groups;
CREATE TABLE Groups (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(255) UNIQUE NOT NULL
);

DROP TABLE IF EXISTS Students;
CREATE TABLE Students (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(255) UNIQUE NOT NULL,
    Group_id INTEGER,
    FOREIGN KEY (Group_id) REFERENCES Groups (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

DROP TABLE IF EXISTS Teachers;
CREATE TABLE Teachers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(255) UNIQUE NOT NULL
);

DROP TABLE IF EXISTS Subjects;
CREATE TABLE Subjects (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(255) NOT NULL,
    Teacher_id INTEGER,
    FOREIGN KEY (Teacher_id) REFERENCES Teachers (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

DROP TABLE IF EXISTS Evaluations;
CREATE TABLE Evaluations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    Rating INTEGER,
    Date DATE NOT NULL,
    Student_id INTEGER,
    Subject_id INTEGER,
    FOREIGN KEY (Student_id) REFERENCES Students (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (Subject_id) REFERENCES Subjects (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);